//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sdi3_37.Cli_C_Sharp.SOAP {
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://admin.impl.business.sdi.com/")]
    public partial class BusinessException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://admin.impl.business.sdi.com/", ConfigurationName="SOAP.AdminService")]
    public interface AdminService {
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_37.Cli_C_Sharp.SOAP.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sdi3_37.Cli_C_Sharp.SOAP.disableUserResponse disableUser(sdi3_37.Cli_C_Sharp.SOAP.disableUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.disableUserResponse> disableUserAsync(sdi3_37.Cli_C_Sharp.SOAP.disableUser request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_37.Cli_C_Sharp.SOAP.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sdi3_37.Cli_C_Sharp.SOAP.listAllUsersResponse listAllUsers(sdi3_37.Cli_C_Sharp.SOAP.listAllUsers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.listAllUsersResponse> listAllUsersAsync(sdi3_37.Cli_C_Sharp.SOAP.listAllUsers request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_37.Cli_C_Sharp.SOAP.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sdi3_37.Cli_C_Sharp.SOAP.enableUserResponse enableUser(sdi3_37.Cli_C_Sharp.SOAP.enableUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.enableUserResponse> enableUserAsync(sdi3_37.Cli_C_Sharp.SOAP.enableUser request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sdi3_37.Cli_C_Sharp.SOAP.findAllUsersResponse findAllUsers(sdi3_37.Cli_C_Sharp.SOAP.findAllUsers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.findAllUsersResponse> findAllUsersAsync(sdi3_37.Cli_C_Sharp.SOAP.findAllUsers request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_37.Cli_C_Sharp.SOAP.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        sdi3_37.Cli_C_Sharp.SOAP.findUserByIdResponse findUserById(sdi3_37.Cli_C_Sharp.SOAP.findUserById request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.findUserByIdResponse> findUserByIdAsync(sdi3_37.Cli_C_Sharp.SOAP.findUserById request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(sdi3_37.Cli_C_Sharp.SOAP.BusinessException), Action="", Name="BusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        sdi3_37.Cli_C_Sharp.SOAP.deepDeleteUserResponse deepDeleteUser(sdi3_37.Cli_C_Sharp.SOAP.deepDeleteUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.deepDeleteUserResponse> deepDeleteUserAsync(sdi3_37.Cli_C_Sharp.SOAP.deepDeleteUser request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="disableUser", WrapperNamespace="http://admin.impl.business.sdi.com/", IsWrapped=true)]
    public partial class disableUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://admin.impl.business.sdi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public disableUser() {
        }
        
        public disableUser(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="disableUserResponse", WrapperNamespace="http://admin.impl.business.sdi.com/", IsWrapped=true)]
    public partial class disableUserResponse {
        
        public disableUserResponse() {
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://admin.impl.business.sdi.com/")]
    public partial class userInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int tareasCompletadasField;
        
        private int tareasCompletadasRetrasadasField;
        
        private int tareasPlanificadasField;
        
        private int tareasSinPlanificarField;
        
        private user userField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int tareasCompletadas {
            get {
                return this.tareasCompletadasField;
            }
            set {
                this.tareasCompletadasField = value;
                this.RaisePropertyChanged("tareasCompletadas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int tareasCompletadasRetrasadas {
            get {
                return this.tareasCompletadasRetrasadasField;
            }
            set {
                this.tareasCompletadasRetrasadasField = value;
                this.RaisePropertyChanged("tareasCompletadasRetrasadas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int tareasPlanificadas {
            get {
                return this.tareasPlanificadasField;
            }
            set {
                this.tareasPlanificadasField = value;
                this.RaisePropertyChanged("tareasPlanificadas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int tareasSinPlanificar {
            get {
                return this.tareasSinPlanificarField;
            }
            set {
                this.tareasSinPlanificarField = value;
                this.RaisePropertyChanged("tareasSinPlanificar");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public user user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://admin.impl.business.sdi.com/")]
    public partial class user : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private bool isAdminField;
        
        private bool isAdminFieldSpecified;
        
        private string loginField;
        
        private string passwordField;
        
        private userStatus statusField;
        
        private bool statusFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool isAdmin {
            get {
                return this.isAdminField;
            }
            set {
                this.isAdminField = value;
                this.RaisePropertyChanged("isAdmin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isAdminSpecified {
            get {
                return this.isAdminFieldSpecified;
            }
            set {
                this.isAdminFieldSpecified = value;
                this.RaisePropertyChanged("isAdminSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public userStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
                this.RaisePropertyChanged("statusSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://admin.impl.business.sdi.com/")]
    public enum userStatus {
        
        /// <comentarios/>
        ENABLED,
        
        /// <comentarios/>
        DISABLED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listAllUsers", WrapperNamespace="http://admin.impl.business.sdi.com/", IsWrapped=true)]
    public partial class listAllUsers {
        
        public listAllUsers() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listAllUsersResponse", WrapperNamespace="http://admin.impl.business.sdi.com/", IsWrapped=true)]
    public partial class listAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://admin.impl.business.sdi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sdi3_37.Cli_C_Sharp.SOAP.userInfo[] @return;
        
        public listAllUsersResponse() {
        }
        
        public listAllUsersResponse(sdi3_37.Cli_C_Sharp.SOAP.userInfo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enableUser", WrapperNamespace="http://admin.impl.business.sdi.com/", IsWrapped=true)]
    public partial class enableUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://admin.impl.business.sdi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public enableUser() {
        }
        
        public enableUser(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enableUserResponse", WrapperNamespace="http://admin.impl.business.sdi.com/", IsWrapped=true)]
    public partial class enableUserResponse {
        
        public enableUserResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllUsers", WrapperNamespace="http://admin.impl.business.sdi.com/", IsWrapped=true)]
    public partial class findAllUsers {
        
        public findAllUsers() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllUsersResponse", WrapperNamespace="http://admin.impl.business.sdi.com/", IsWrapped=true)]
    public partial class findAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://admin.impl.business.sdi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sdi3_37.Cli_C_Sharp.SOAP.user[] @return;
        
        public findAllUsersResponse() {
        }
        
        public findAllUsersResponse(sdi3_37.Cli_C_Sharp.SOAP.user[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findUserById", WrapperNamespace="http://admin.impl.business.sdi.com/", IsWrapped=true)]
    public partial class findUserById {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://admin.impl.business.sdi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public findUserById() {
        }
        
        public findUserById(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findUserByIdResponse", WrapperNamespace="http://admin.impl.business.sdi.com/", IsWrapped=true)]
    public partial class findUserByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://admin.impl.business.sdi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sdi3_37.Cli_C_Sharp.SOAP.user @return;
        
        public findUserByIdResponse() {
        }
        
        public findUserByIdResponse(sdi3_37.Cli_C_Sharp.SOAP.user @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deepDeleteUser", WrapperNamespace="http://admin.impl.business.sdi.com/", IsWrapped=true)]
    public partial class deepDeleteUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://admin.impl.business.sdi.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public deepDeleteUser() {
        }
        
        public deepDeleteUser(long arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deepDeleteUserResponse", WrapperNamespace="http://admin.impl.business.sdi.com/", IsWrapped=true)]
    public partial class deepDeleteUserResponse {
        
        public deepDeleteUserResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminServiceChannel : sdi3_37.Cli_C_Sharp.SOAP.AdminService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminServiceClient : System.ServiceModel.ClientBase<sdi3_37.Cli_C_Sharp.SOAP.AdminService>, sdi3_37.Cli_C_Sharp.SOAP.AdminService {
        
        public AdminServiceClient() {
        }
        
        public AdminServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_37.Cli_C_Sharp.SOAP.disableUserResponse sdi3_37.Cli_C_Sharp.SOAP.AdminService.disableUser(sdi3_37.Cli_C_Sharp.SOAP.disableUser request) {
            return base.Channel.disableUser(request);
        }
        
        public void disableUser(long arg0) {
            sdi3_37.Cli_C_Sharp.SOAP.disableUser inValue = new sdi3_37.Cli_C_Sharp.SOAP.disableUser();
            inValue.arg0 = arg0;
            sdi3_37.Cli_C_Sharp.SOAP.disableUserResponse retVal = ((sdi3_37.Cli_C_Sharp.SOAP.AdminService)(this)).disableUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.disableUserResponse> sdi3_37.Cli_C_Sharp.SOAP.AdminService.disableUserAsync(sdi3_37.Cli_C_Sharp.SOAP.disableUser request) {
            return base.Channel.disableUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.disableUserResponse> disableUserAsync(long arg0) {
            sdi3_37.Cli_C_Sharp.SOAP.disableUser inValue = new sdi3_37.Cli_C_Sharp.SOAP.disableUser();
            inValue.arg0 = arg0;
            return ((sdi3_37.Cli_C_Sharp.SOAP.AdminService)(this)).disableUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_37.Cli_C_Sharp.SOAP.listAllUsersResponse sdi3_37.Cli_C_Sharp.SOAP.AdminService.listAllUsers(sdi3_37.Cli_C_Sharp.SOAP.listAllUsers request) {
            return base.Channel.listAllUsers(request);
        }
        
        public sdi3_37.Cli_C_Sharp.SOAP.userInfo[] listAllUsers() {
            sdi3_37.Cli_C_Sharp.SOAP.listAllUsers inValue = new sdi3_37.Cli_C_Sharp.SOAP.listAllUsers();
            sdi3_37.Cli_C_Sharp.SOAP.listAllUsersResponse retVal = ((sdi3_37.Cli_C_Sharp.SOAP.AdminService)(this)).listAllUsers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.listAllUsersResponse> sdi3_37.Cli_C_Sharp.SOAP.AdminService.listAllUsersAsync(sdi3_37.Cli_C_Sharp.SOAP.listAllUsers request) {
            return base.Channel.listAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.listAllUsersResponse> listAllUsersAsync() {
            sdi3_37.Cli_C_Sharp.SOAP.listAllUsers inValue = new sdi3_37.Cli_C_Sharp.SOAP.listAllUsers();
            return ((sdi3_37.Cli_C_Sharp.SOAP.AdminService)(this)).listAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_37.Cli_C_Sharp.SOAP.enableUserResponse sdi3_37.Cli_C_Sharp.SOAP.AdminService.enableUser(sdi3_37.Cli_C_Sharp.SOAP.enableUser request) {
            return base.Channel.enableUser(request);
        }
        
        public void enableUser(long arg0) {
            sdi3_37.Cli_C_Sharp.SOAP.enableUser inValue = new sdi3_37.Cli_C_Sharp.SOAP.enableUser();
            inValue.arg0 = arg0;
            sdi3_37.Cli_C_Sharp.SOAP.enableUserResponse retVal = ((sdi3_37.Cli_C_Sharp.SOAP.AdminService)(this)).enableUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.enableUserResponse> sdi3_37.Cli_C_Sharp.SOAP.AdminService.enableUserAsync(sdi3_37.Cli_C_Sharp.SOAP.enableUser request) {
            return base.Channel.enableUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.enableUserResponse> enableUserAsync(long arg0) {
            sdi3_37.Cli_C_Sharp.SOAP.enableUser inValue = new sdi3_37.Cli_C_Sharp.SOAP.enableUser();
            inValue.arg0 = arg0;
            return ((sdi3_37.Cli_C_Sharp.SOAP.AdminService)(this)).enableUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_37.Cli_C_Sharp.SOAP.findAllUsersResponse sdi3_37.Cli_C_Sharp.SOAP.AdminService.findAllUsers(sdi3_37.Cli_C_Sharp.SOAP.findAllUsers request) {
            return base.Channel.findAllUsers(request);
        }
        
        public sdi3_37.Cli_C_Sharp.SOAP.user[] findAllUsers() {
            sdi3_37.Cli_C_Sharp.SOAP.findAllUsers inValue = new sdi3_37.Cli_C_Sharp.SOAP.findAllUsers();
            sdi3_37.Cli_C_Sharp.SOAP.findAllUsersResponse retVal = ((sdi3_37.Cli_C_Sharp.SOAP.AdminService)(this)).findAllUsers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.findAllUsersResponse> sdi3_37.Cli_C_Sharp.SOAP.AdminService.findAllUsersAsync(sdi3_37.Cli_C_Sharp.SOAP.findAllUsers request) {
            return base.Channel.findAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.findAllUsersResponse> findAllUsersAsync() {
            sdi3_37.Cli_C_Sharp.SOAP.findAllUsers inValue = new sdi3_37.Cli_C_Sharp.SOAP.findAllUsers();
            return ((sdi3_37.Cli_C_Sharp.SOAP.AdminService)(this)).findAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_37.Cli_C_Sharp.SOAP.findUserByIdResponse sdi3_37.Cli_C_Sharp.SOAP.AdminService.findUserById(sdi3_37.Cli_C_Sharp.SOAP.findUserById request) {
            return base.Channel.findUserById(request);
        }
        
        public sdi3_37.Cli_C_Sharp.SOAP.user findUserById(long arg0) {
            sdi3_37.Cli_C_Sharp.SOAP.findUserById inValue = new sdi3_37.Cli_C_Sharp.SOAP.findUserById();
            inValue.arg0 = arg0;
            sdi3_37.Cli_C_Sharp.SOAP.findUserByIdResponse retVal = ((sdi3_37.Cli_C_Sharp.SOAP.AdminService)(this)).findUserById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.findUserByIdResponse> sdi3_37.Cli_C_Sharp.SOAP.AdminService.findUserByIdAsync(sdi3_37.Cli_C_Sharp.SOAP.findUserById request) {
            return base.Channel.findUserByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.findUserByIdResponse> findUserByIdAsync(long arg0) {
            sdi3_37.Cli_C_Sharp.SOAP.findUserById inValue = new sdi3_37.Cli_C_Sharp.SOAP.findUserById();
            inValue.arg0 = arg0;
            return ((sdi3_37.Cli_C_Sharp.SOAP.AdminService)(this)).findUserByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        sdi3_37.Cli_C_Sharp.SOAP.deepDeleteUserResponse sdi3_37.Cli_C_Sharp.SOAP.AdminService.deepDeleteUser(sdi3_37.Cli_C_Sharp.SOAP.deepDeleteUser request) {
            return base.Channel.deepDeleteUser(request);
        }
        
        public void deepDeleteUser(long arg0) {
            sdi3_37.Cli_C_Sharp.SOAP.deepDeleteUser inValue = new sdi3_37.Cli_C_Sharp.SOAP.deepDeleteUser();
            inValue.arg0 = arg0;
            sdi3_37.Cli_C_Sharp.SOAP.deepDeleteUserResponse retVal = ((sdi3_37.Cli_C_Sharp.SOAP.AdminService)(this)).deepDeleteUser(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.deepDeleteUserResponse> sdi3_37.Cli_C_Sharp.SOAP.AdminService.deepDeleteUserAsync(sdi3_37.Cli_C_Sharp.SOAP.deepDeleteUser request) {
            return base.Channel.deepDeleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<sdi3_37.Cli_C_Sharp.SOAP.deepDeleteUserResponse> deepDeleteUserAsync(long arg0) {
            sdi3_37.Cli_C_Sharp.SOAP.deepDeleteUser inValue = new sdi3_37.Cli_C_Sharp.SOAP.deepDeleteUser();
            inValue.arg0 = arg0;
            return ((sdi3_37.Cli_C_Sharp.SOAP.AdminService)(this)).deepDeleteUserAsync(inValue);
        }
    }
}
